name: apollo
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - biopython=1.74
  - coreutils=8.25
  - mafft
  - minimap2=2.17
  - pip=19.3.1
  - python=3.6
  - snakemake-minimal=5.13
  - pip:
    - msgpack==0.6.2
    - parasail==1.2
    # - matplotlib==3.1.1
